### ISSUE TITLE
CA.crt变动问题

### ISSUE THREAD

**Issue by zhoupro** [codezm/Docker-XX-Net#2]
改动yml文件，执行docker-compose up -d,CA.crt文件变动。场景，服务器可以修改yml来实现是否开启管理界面，以及切换代理端口

**Comment by codezm** [comment]
`CA.crt文件变动` 是什么意思？`服务器使用 导入证书` 此处的服务器是指`docker`吗？

**Comment by codezm** [comment]
感谢反馈，已在 `docker-compose.yml` 中挂载`xx-net` 相关配置文件.

**Comment by zhoupro** [comment]
真棒
