### ISSUE TITLE
这个项目做得就是把xtutle客户端和GAE连接的这个过程做了是吧

### ISSUE THREAD

**Issue by xx-zhang** [codezm/Docker-XX-Net#8]
就是省略了本地部署修改隧道，开启ipv6这个过程

**Comment by xx-zhang** [comment]
我以为把浏览器都集成进去了， 证书代理都在里面直接暴露一个socks5或者http就可以在任何环境下甚至是路由器中使用，

**Comment by xx-zhang** [comment]
部署一切正常 浏览器证书错误。 你这个就是把本地的 xx-net-app管控服务端和隧道放在远程了 实际上windows下本机搭建也很简单，当然怕污染了本地的端口可以这样。

**Comment by codezm** [comment]
嗯，利用 Docker 环境部署可以避免本机环境污染，浏览器证书错误可以看看 README.md 有解决方案。

**Comment by xx-zhang** [comment]
嗯， 嗯 我后来都正常了。
